import { Gaegu } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import NavBar from "./NavBar";

export const metadata = {
  title: "Procrasti-nation",
  description: "Generated by Next.js",
};

const gaegu = Gaegu({
  weight: "400",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main>
          <div className={gaegu.className}>
            <NavBar />
          </div>
          {children}
        </main>
      </body>
    </html>
  );
}
